services:

  postgresql_db:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: shaan
      POSTGRES_PASSWORD: shaan123